/*
For PluginMapBox - Modified Version        
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import Logo from '../Logo'
import Unit from '../Unit'
import GrayArea from '../GrayArea'
import { useCountRenders } from '../../hooks/useCountRenders'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'models/Ground_3D_1.1.1.glb')

  useCountRenders('Map Model:' + props.name)

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <Unit geometry={nodes.Unit_GA29.geometry} name="Unit_GA29" position={[16.95, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA28.geometry} name="Unit_GA28" position={[14.68, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA27.geometry} name="Unit_GA27" position={[11.69, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA26.geometry} name="Unit_GA26" position={[8.61, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA23a.geometry} name="Unit_GA23a" position={[4.27, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA21.geometry} name="Unit_GA21" position={[2.29, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA20.geometry} name="Unit_GA20" position={[0.21, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA19.geometry} name="Unit_GA19" position={[-1.49, 0, -8.82]} />
        <Unit geometry={nodes.Unit_GA16.geometry} name="Unit_GA16" position={[-2.87, 0, -8.82]} />
        <Unit geometry={nodes.Unit_Gxx01.geometry} name="Unit_Gxx01" position={[21.09, 0, -8.82]} />
        <Unit geometry={nodes.Unit_G00.geometry} name="Unit_G00" position={[20.32, 0, -7.13]} />
        <Unit geometry={nodes.Unit_G29.geometry} name="Unit_G29" position={[16.95, 0, -6.34]} />
        <Unit geometry={nodes.Unit_G28.geometry} name="Unit_G28" position={[14.53, 0, -6.34]} />
        <Unit geometry={nodes.Unit_G27.geometry} name="Unit_G27" position={[12.18, 0, -6.34]} />
        <Unit geometry={nodes.Unit_G26.geometry} name="Unit_G26" position={[9.95, 0, -6.34]} />
        <Unit geometry={nodes.Unit_G25.geometry} name="Unit_G25" position={[7.65, 0, -4.91]} />
        <Unit geometry={nodes.Unit_G23a.geometry} name="Unit_G23a" position={[4.29, 0, -5.43]} />
        <Unit geometry={nodes.Unit_G21.geometry} name="Unit_G21" position={[2.43, 0, -5.43]} />
        <Unit geometry={nodes.Unit_G20.geometry} name="Unit_G20" position={[0.19, 0, -5.43]} />
        <Unit geometry={nodes.Unit_G19.geometry} name="Unit_G19" position={[-2.02, 0, -5.43]} />
        <Unit geometry={nodes.Unit_G16.geometry} name="Unit_G16" position={[-3.58, 0, -6.18]} />
        <Unit geometry={nodes.Unit_GD16.geometry} name="Unit_GD16" position={[-4.02, 0, -6.4]} />
        <Unit geometry={nodes.Unit_G17.geometry} name="Unit_G17" position={[-4.34, 0, -4.55]} />
        <Unit geometry={nodes.Unit_GD17.geometry} name="Unit_GD17" position={[-4.97, 0, -4.37]} />
        <Unit geometry={nodes.Unit_G18.geometry} name="Unit_G18" position={[-4.34, 0, -2.46]} />
        <Unit geometry={nodes.Unit_GK01.geometry} name="Unit_GK01" position={[-5.01, 0, -1]} />
        <Unit geometry={nodes.Unit_GK02.geometry} name="Unit_GK02" position={[-1.93, 0, -0.77]} />
        <Unit geometry={nodes.Unit_GK03.geometry} name="Unit_GK03" position={[4.12, 0, -0.77]} />
        <Unit geometry={nodes.Unit_G01a.geometry} name="Unit_G01a" position={[20.82, 0, -1.77]} />
        <Unit geometry={nodes.Unit_G01.geometry} name="Unit_G01" position={[14.36, 0, 7.01]} />
        <Unit geometry={nodes.Unit_G03.geometry} name="Unit_G03" position={[7.14, 0, 7.01]} />
        <Unit geometry={nodes.Unit_G02.geometry} name="Unit_G02" position={[12.23, 0, 3.61]} />
        <Unit geometry={nodes.Unit_G03a.geometry} name="Unit_G03a" position={[0.17, 0, 7.01]} />
        <Unit geometry={nodes.Unit_G05.geometry} name="Unit_G05" position={[-8.48, 0, 5.8]} />
        <Unit geometry={nodes.Unit_G07.geometry} name="Unit_G07" position={[-8.24, 0, 0.97]} />
        <Unit geometry={nodes.Unit_G06.geometry} name="Unit_G06" position={[-9.05, 0, 2.7]} />
        <Unit geometry={nodes.Unit_G09.geometry} name="Unit_G09" position={[-17.58, 0, 3.73]} />
        <Unit geometry={nodes.Unit_G10.geometry} name="Unit_G10" position={[-16.07, 0, -0.5]} />
        <Unit geometry={nodes.Unit_G11.geometry} name="Unit_G11" position={[-16.07, 0, -2.47]} />
        <Unit geometry={nodes.Unit_G12.geometry} name="Unit_G12" position={[-15.1, 0, -4.58]} />
        <Unit geometry={nodes.Unit_G13.geometry} name="Unit_G13" position={[-14.14, 0, -6.6]} />
        <Unit geometry={nodes.Unit_G13a.geometry} name="Unit_G13a" position={[-13.32, 0, -9.09]} />
        <Unit geometry={nodes.Unit_GK09.geometry} name="Unit_GK09" position={[-8, 0, -9.04]} />
        <Unit geometry={nodes.Unit_G23.geometry} name="Unit_G23" position={[4.92, 0, -2.65]} />
        <Unit geometry={nodes.Unit_GC01.geometry} name="Unit_GC01" position={[19.96, 0, 5.73]} />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service003.geometry}
          name="Service003"
          position={[-18.17, 0, -1.16]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service004.geometry}
          name="Service004"
          position={[-18.96, 0, -4.14]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service001.geometry}
          name="Service001"
          position={[-1.27, 0, -11.43]}
        />
        <mesh
          material={materials['Lift.Normal']}
          geometry={nodes.Lift002.geometry}
          name="Lift002"
          position={[5.19, 0, -6.37]}
        />
        <mesh
          material={materials['Lift.Normal']}
          geometry={nodes.Lift001.geometry}
          name="Lift001"
          position={[-8.78, 0, -9.36]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator005.geometry}
          name="Escalator005"
          position={[11.2, 0.47, -3.25]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator006.geometry}
          name="Escalator006"
          position={[11.2, 0.47, -2.93]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator001.geometry}
          name="Escalator001"
          position={[-9.96, 0.47, -6.43]}
          rotation={[Math.PI / 2, 0, -1.13]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator002.geometry}
          name="Escalator002"
          position={[-9.67, 0.47, -6.29]}
          rotation={[Math.PI / 2, 0, -1.13]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator004.geometry}
          name="Escalator004"
          position={[-4.74, -0.33, -3.98]}
          rotation={[Math.PI / 2, 0, 0.44]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator003.geometry}
          name="Escalator003"
          position={[-4.88, -0.33, -3.7]}
          rotation={[Math.PI / 2, 0, 0.44]}
        />
        <mesh
          material={materials['Utilities.Normal']}
          geometry={nodes.Utilities001.geometry}
          name="Utilities001"
          position={[18.44, 0, 9.83]}
        />
        <mesh
          material={materials.Floor}
          geometry={nodes.Floor.geometry}
          name="Floor"
          position={[0, 0, 0]}
          receiveShadow
        />
        <mesh
          material={materials['Others.Normal']}
          geometry={nodes.Others001.geometry}
          name="Others001"
          position={[18.64, 0, -6.41]}
        />
        <mesh
          material={materials['Others.Normal']}
          geometry={nodes.Others002.geometry}
          name="Others002"
          position={[18.64, 0, -0.59]}
        />
        <mesh
          material={materials['Others.Normal']}
          geometry={nodes.Others003.geometry}
          name="Others003"
          position={[-6.26, 0, -9.28]}
        />
        <mesh
          material={materials['Others.Normal.001']}
          geometry={nodes.Others004.geometry}
          name="Others004"
          position={[6.04, 0, -7.37]}
        />
        <GrayArea geometry={nodes.NoEntry001.geometry} name="NoEntry001" receiveShadow />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse001.geometry}
          name="DalaHorse001"
          position={[-6.7, 0, -11.57]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse002.geometry}
          name="DalaHorse002"
          position={[6.32, 0, -10.41]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse003.geometry}
          name="DalaHorse003"
          position={[6.14, 0, -9.5]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse004.geometry}
          name="DalaHorse004"
          position={[5.91, 0, -9.87]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse005.geometry}
          name="DalaHorse005"
          position={[6.59, 0, -10.11]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse006.geometry}
          name="DalaHorse006"
          position={[19.06, 0, -9.76]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse007.geometry}
          name="DalaHorse007"
          position={[19.75, 0, -10.07]}
          rotation={[Math.PI / 2, 0, Math.PI]}
        />
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse008.geometry}
          name="DalaHorse008"
          position={[19.52, 0, -10.51]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={[1.04, 1.04, 1.04]}
        />
        <group name="Icon_ATMG01" position={[-14.36, 1, -3.47]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.002_0'].geometry} name="Curve.002_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.002_1'].geometry} name="Curve.002_1" />
        </group>
        <group name="Icon_ToiletMaleG01" position={[-18.51, 1, -4.76]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.013_0'].geometry} name="Curve.013_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.013_1'].geometry} name="Curve.013_1" />
        </group>
        <group name="Icon_ToiletDisableG01" position={[-19.01, 1, -3.67]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.018_0'].geometry} name="Curve.018_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.018_1'].geometry} name="Curve.018_1" />
        </group>
        <group name="Icon_ToiletFemaleG01" position={[-19.55, 1, -2.59]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.032_0'].geometry} name="Curve.032_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.032_1'].geometry} name="Curve.032_1" />
        </group>
        <group name="Icon_LiftG01" position={[-8.82, 1, -8.78]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.037_0'].geometry} name="Curve.037_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.037_1'].geometry} name="Curve.037_1" />
        </group>
        <group name="Icon_LiftG02" position={[5.21, 1, -5.84]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.046_0'].geometry} name="Curve.046_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.046_1'].geometry} name="Curve.046_1" />
        </group>
        <group name="Icon_EscalatorG01" position={[-9.75, 1, -6.51]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.044_0'].geometry} name="Curve.044_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.044_1'].geometry} name="Curve.044_1" />
        </group>
        <group name="Icon_EscalatorG02" position={[-5.25, 1, -3.52]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.038_0'].geometry} name="Curve.038_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.038_1'].geometry} name="Curve.038_1" />
        </group>
        <group name="Icon_EscalatorG03" position={[11.19, 1, -2.84]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.045_0'].geometry} name="Curve.045_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.045_1'].geometry} name="Curve.045_1" />
        </group>
        <group name="Icon_FirtAidG01" position={[-17.71, 1, -0.87]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.049_0'].geometry} name="Curve.049_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.049_1'].geometry} name="Curve.049_1" />
        </group>
        <group name="Icon_FamilyG01" position={[-18.66, 1, -0.62]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.065_0'].geometry} name="Curve.065_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.065_1'].geometry} name="Curve.065_1" />
        </group>
        <group name="Icon_iCounterG01" position={[9.77, 0, -2.26]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.069_0'].geometry} name="Curve.069_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.069_1'].geometry} name="Curve.069_1" />
        </group>
        <group name="Icon_BicycleG01" position={[18.05, 1, -11.19]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.077_0'].geometry} name="Curve.077_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.077_1'].geometry} name="Curve.077_1" />
        </group>
        <group name="Icon_EntranceG01" position={[-6.05, 0, -9.15]}>
          <mesh material={materials['IconGreen.Normal']} geometry={nodes['Curve.079_0'].geometry} name="Curve.079_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.079_1'].geometry} name="Curve.079_1" />
        </group>
        <group name="Icon_EntranceG02" position={[6.12, 0, -7.37]}>
          <mesh material={materials['IconGreen.Normal']} geometry={nodes['Curve.080_0'].geometry} name="Curve.080_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.080_1'].geometry} name="Curve.080_1" />
        </group>
        <group name="Icon_EntranceG03" position={[18.68, 0, -5.9]}>
          <mesh material={materials['IconGreen.Normal']} geometry={nodes['Curve.081_0'].geometry} name="Curve.081_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.081_1'].geometry} name="Curve.081_1" />
        </group>
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_AlfrescoG01.geometry}
          name="Text_AlfrescoG01"
          position={[1.37, 0, -10.13]}
        />
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_AlfrescoG02.geometry}
          name="Text_AlfrescoG02"
          position={[13.21, 0, -10.13]}
        />
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_ConcourseG01.geometry}
          name="Text_ConcourseG01"
          position={[-8.06, 0, -5.35]}
        />
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_CourtyardG01.geometry}
          name="Text_CourtyardG01"
          position={[19.96, 0.2, 5.94]}
        />
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_MidlandG01.geometry}
          name="Text_MidlandG01"
          position={[7.96, 0, -2.71]}
        />
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_SmalandG01.geometry}
          name="Text_SmalandG01"
          position={[18.14, 0, -2.73]}
        />
        <Logo
          material={materials['HM.Normal']}
          geometry={nodes['Logo_H&M'].geometry}
          name="Logo_H&M"
          position={[15.64, 1, 7.18]}
        />
        <Logo
          material={materials['LcWaikiki.Normal']}
          geometry={nodes.Logo_LcWaikiki.geometry}
          name="Logo_LcWaikiki"
          position={[-8.87, 1, 6.27]}
        />
        <Logo
          material={materials['BO.Normal']}
          geometry={nodes.Logo_BO.geometry}
          name="Logo_BO"
          position={[0.12, 1, 7.18]}
        />
        <Logo
          material={materials['Padini.Normal']}
          geometry={nodes.Logo_Padini.geometry}
          name="Logo_Padini"
          position={[7.49, 1, 7.24]}
        />
      </scene>
    </group>
  )
}
