/*
For PluginMapBox - Modified Version        
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import Logo from '../Logo'
import Unit from '../Unit'
import GrayArea from '../GrayArea'
import { useCountRenders } from '../../hooks/useCountRenders'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'models/Level2_3D_1.5.glb')

  useCountRenders('Map Model:' + props.name)

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <mesh
          material={nodes.Service_L24.material}
          geometry={nodes.Service_L24.geometry}
          name="Service_L24"
          position={[-15.43, 0, -8.62]}
        />
        <mesh
          material={materials.Floor}
          geometry={nodes.Floor.geometry}
          name="Floor"
          scale={[15.36, 15.36, 15.36]}
          receiveShadow
        />
        <mesh
          material={materials['Utilities.Normal']}
          geometry={nodes.Utilities_L21.geometry}
          name="Utilities_L21"
          position={[8.94, 0, -5.88]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service_L21.geometry}
          name="Service_L21"
          position={[18.14, 0, 0.47]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service_L22.geometry}
          name="Service_L22"
          position={[18.14, 0, 3.28]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service_L23.geometry}
          name="Service_L23"
          position={[-17.9, 0, -3.75]}
        />
        <mesh
          material={materials['Services.Normal']}
          geometry={nodes.Service_L25.geometry}
          name="Service_L25"
          position={[19.14, 0, 4.88]}
        />
        <mesh
          material={materials['Lift.Normal']}
          geometry={nodes.Lift_L21.geometry}
          name="Lift_L21"
          position={[6.66, 0, -6.36]}
        />
        <mesh
          material={materials['Lift.Normal']}
          geometry={nodes.Lift_L22.geometry}
          name="Lift_L22"
          position={[-6.95, 0, -8.79]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator_L25.geometry}
          name="Escalator_L25"
          position={[-11.97, 0, 5.64]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator_L22.geometry}
          name="Escalator_L22"
          position={[-7.9, -0.33, -4.98]}
          rotation={[-Math.PI / 2, 0, -2.01]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator_L21.geometry}
          name="Escalator_L21"
          position={[-8.19, -0.33, -5.12]}
          rotation={[-Math.PI / 2, 0, -2.01]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator_L23.geometry}
          name="Escalator_L23"
          position={[12.07, -0.33, -3.24]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          material={materials['Escalator.Normal']}
          geometry={nodes.Escalator_L24.geometry}
          name="Escalator_L24"
          position={[12.07, -0.33, -2.93]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <Unit geometry={nodes.Unit_L223a.geometry} name="Unit_L2.23a" position={[14.67, 0, -5.91]} />
        <Unit geometry={nodes.Unit_L223.geometry} name="Unit_L2.23" position={[12.81, 0, -5.93]} />
        <Unit geometry={nodes.Unit_L2xx11.geometry} name="Unit_L2.xx11" position={[11.01, 0, -5.98]} />
        <Unit geometry={nodes.Unit_L221.geometry} name="Unit_L2.21" position={[8.9, 0, -4.74]} />
        <Unit geometry={nodes.Unit_L225.geometry} name="Unit_L2.25" position={[16.92, 0, -4.64]} />
        <Unit geometry={nodes.Unit_L218.geometry} name="Unit_L2.18" position={[3.52, 0, -4.25]} />
        <Unit geometry={nodes.Unit_L219.geometry} name="Unit_L2.19" position={[5.32, 0, -4.93]} />
        <Unit geometry={nodes.Unit_L220.geometry} name="Unit_L2.20" position={[5.62, 0, -2.58]} />
        <Unit geometry={nodes.Unit_L217.geometry} name="Unit_L2.17" position={[1.66, 0, -4.25]} />
        <Unit geometry={nodes.Unit_L216.geometry} name="Unit_L2.16" position={[-0.08, 0, -1.92]} />
        <Unit geometry={nodes.Unit_L215.geometry} name="Unit_L2.15" position={[-0.08, 0, -2.56]} />
        <Unit geometry={nodes.Unit_L2xx02.geometry} name="Unit_L2.xx02" position={[-0.08, 0, -3.22]} />
        <Unit geometry={nodes.Unit_L211.geometry} name="Unit_L2.11" position={[-1, 0, -5.89]} />
        <Unit geometry={nodes.Unit_L2xx03.geometry} name="Unit_L2.xx03" position={[1.46, 0, -0.77]} />
        <Unit geometry={nodes.Unit_L2xx05.geometry} name="Unit_L2.xx05" position={[-2.38, 0, -2]} />
        <Unit geometry={nodes.Unit_L2xx06.geometry} name="Unit_L2.xx06" position={[-5.48, 0, -2.69]} />
        <Unit geometry={nodes.Unit_L2xx07.geometry} name="Unit_L2.xx07" position={[-5, 0, -3.71]} />
        <Unit geometry={nodes.Unit_L2xx04.geometry} name="Unit_L2.xx04" position={[-4.58, 0, -4.59]} />
        <Unit geometry={nodes.Unit_L2xx08.geometry} name="Unit_L2.xx08" position={[-6.04, 0, -4.17]} />
        <Unit geometry={nodes.Unit_L2xx09.geometry} name="Unit_L2.xx09" position={[-8.57, 0, -4.02]} />
        <Unit geometry={nodes.Unit_L2xx10.geometry} name="Unit_L2.xx10" position={[-10.34, 0, -4.53]} />
        <Unit geometry={nodes.Unit_L2xx01.geometry} name="Unit_L2.xx01" position={[-9.75, 0, -9.73]} />
        <Unit geometry={nodes.Unit_L209.geometry} name="Unit_L2.09" position={[-12.63, 0, -9.56]} />
        <Unit geometry={nodes.Unit_L208.geometry} name="Unit_L2.08" position={[-15.51, 0, -2.28]} />
        <Unit geometry={nodes.Unit_L207.geometry} name="Unit_L2.07" position={[-10.3, 0, 4.67]} />
        <Unit geometry={nodes.Unit_L206.geometry} name="Unit_L2.06" position={[-1.9, 0, 4.48]} />
        <Unit geometry={nodes.Unit_L203.geometry} name="Unit_L2.03" position={[5.79, 0, 6.93]} />
        <Unit geometry={nodes.Unit_L203a.geometry} name="Unit_L2.03a" position={[3.49, 0, 1.24]} />
        <Unit geometry={nodes.Unit_L2xx13.geometry} name="Unit_L2.xx13" position={[1.44, 0, 1.52]} />
        <Unit geometry={nodes.Unit_L202.geometry} name="Unit_L2.02" position={[14.66, 0, 7.58]} />
        <Unit geometry={nodes.Unit_L2xx14.geometry} name="Unit_L2.xx14" position={[16.33, 0, 0]} />
        <Unit geometry={nodes.Unit_L2K08.geometry} name="Unit_L2.K08" position={[8.66, 0, -2.64]} />
        <Unit geometry={nodes.Unit_L2K09.geometry} name="Unit_L2.K09" position={[12.41, 0, -1.3]} />
        <Unit geometry={nodes.Unit_L2xx12.geometry} name="Unit_L2.xx12" position={[-3.22, 0, -2.95]} />
        <GrayArea geometry={nodes.NoEntry_L21.geometry} name="NoEntry_L21" position={[3.13, 0, 1.05]} receiveShadow />
        <Logo
          material={materials['HarveyNorman.Normal']}
          geometry={nodes.Logo_HarveyNorman.geometry}
          name="Logo_HarveyNorman"
          position={[-9.87, 1, 2.85]}
          connectTo="Unit_L2.07"
        />
        <Logo name="Logo_Toysrus" position={[-1.83, 1, 5.69]} scale={[5.53, 5.53, 5.53]} connectTo="Unit_L2.06">
          <mesh
            material={materials['ToysrusWhite.Normal']}
            geometry={nodes['Curve.025_0'].geometry}
            name="Curve.025_0"
          />
          <mesh
            material={materials['ToysrusBlue.Normal']}
            geometry={nodes['Curve.025_1'].geometry}
            name="Curve.025_1"
          />
          <mesh
            material={materials['ToysrusOrange.Normal']}
            geometry={nodes['Curve.025_2'].geometry}
            name="Curve.025_2"
          />
          <mesh
            material={materials['ToysrusGreen.Normal']}
            geometry={nodes['Curve.025_3'].geometry}
            name="Curve.025_3"
          />
          <mesh
            material={materials['ToysrusPink.Normal']}
            geometry={nodes['Curve.025_4'].geometry}
            name="Curve.025_4"
          />
        </Logo>
        <Logo
          material={materials['Popular.Normal']}
          geometry={nodes.Logo_Popular.geometry}
          name="Logo_Popular"
          position={[5.96, 1, 6.74]}
          scale={[9.58, 9.58, 9.58]}
          connectTo="Unit_L2.03"
        />
        <Logo name="Logo_Spotlight" position={[14.58, 1, 6.83]} scale={[9.14, 9.14, 9.14]} connectTo="Unit_L2.02">
          <mesh
            material={materials['SpotlightRed.Normal']}
            geometry={nodes['Curve.038_0'].geometry}
            name="Curve.038_0"
          />
          <mesh
            material={materials['SpotlightBlue.Normal']}
            geometry={nodes['Curve.038_1'].geometry}
            name="Curve.038_1"
          />
          <mesh
            material={materials['SpotlightWhite.Normal']}
            geometry={nodes['Curve.038_2'].geometry}
            name="Curve.038_2"
          />
        </Logo>
        <mesh
          material={materials['DalaHorse.Normal']}
          geometry={nodes.DalaHorse_L21.geometry}
          name="DalaHorse_L21"
          position={[-6.18, 0, -6.19]}
          rotation={[0, 0, Math.PI]}
        />
        <group name="Icon_Escalator_G_1" position={[-7.9, 1, -4.94]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.044_0'].geometry} name="Curve.044_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.044_1'].geometry} name="Curve.044_1" />
        </group>
        <group name="Icon_Escalator_G_2" position={[-11.45, 1, 6.1]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.045_0'].geometry} name="Curve.045_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.045_1'].geometry} name="Curve.045_1" />
        </group>
        <group name="Icon_Escalator_G_3" position={[11.61, 1, -2.51]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.047_0'].geometry} name="Curve.047_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.047_1'].geometry} name="Curve.047_1" />
        </group>
        <group name="Icon_Family_G_1" position={[-15.47, 1, -8.05]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.065_0'].geometry} name="Curve.065_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.065_1'].geometry} name="Curve.065_1" />
        </group>
        <group name="Icon_Lift_G_1" position={[-7.16, 1, -8.71]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.043_0'].geometry} name="Curve.043_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.043_1'].geometry} name="Curve.043_1" />
        </group>
        <group name="Icon_Lift_G_2" position={[6.65, 1, -5.81]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.046_0'].geometry} name="Curve.046_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.046_1'].geometry} name="Curve.046_1" />
        </group>
        <group name="Icon_Toilet_L2Disabled_1" position={[-17.83, 1, -3.29]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.041_0'].geometry} name="Curve.041_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.041_1'].geometry} name="Curve.041_1" />
        </group>
        <group name="Icon_Toilet_L2Female_1" position={[-18.39, 1, -2.1]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.042_0'].geometry} name="Curve.042_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.042_1'].geometry} name="Curve.042_1" />
        </group>
        <group name="Icon_Toilet_L2Male_1" position={[-17.3, 1, -4.43]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.040_0'].geometry} name="Curve.040_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.040_1'].geometry} name="Curve.040_1" />
        </group>
        <group name="Icon_Toilet_L2Disabled_2" position={[19.15, 1, 5.45]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.051_0'].geometry} name="Curve.051_0" />
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.051_1'].geometry} name="Curve.051_1" />
        </group>
        <group name="Icon_Toilet_L2Female_2" position={[18.13, 1, 4.43]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.050_0'].geometry} name="Curve.050_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.050_1'].geometry} name="Curve.050_1" />
        </group>
        <group name="Icon_Toilet_L2Male_2" position={[18.14, 1, 3.25]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.048_0'].geometry} name="Curve.048_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.048_1'].geometry} name="Curve.048_1" />
        </group>
        <group name="Icon_Family_G_2" position={[18.15, 1, 1.03]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.052_0'].geometry} name="Curve.052_0" />
          <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.052_1'].geometry} name="Curve.052_1" />
        </group>
        <mesh
          material={materials['Text.Normal']}
          geometry={nodes.Text_L21.geometry}
          name="Text_L21"
          position={[-3.17, 0.1, -2.86]}
          scale={[20, 20, 20]}
        />
      </scene>
    </group>
  )
}
