/*
For PluginMapBox - Modified Version        
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import Logo from '../Logo'
import Unit from '../Unit'
import GrayArea from '../GrayArea'
import { useCountRenders } from '../../hooks/useCountRenders'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, 'models/Level1_3D_1.6.glb')

  useCountRenders('Map Model:' + props.name)

  return (
    <group ref={group} {...props} dispose={null}>
      <Unit geometry={nodes.Unit_L101.geometry} name="Unit_L1.01" position={[17.65, 0, 1.01]} />
      <Unit geometry={nodes.Unit_L102.geometry} name="Unit_L1.02" position={[13.57, 0, 6.87]} />
      <Unit geometry={nodes.Unit_L103.geometry} name="Unit_L1.03" position={[11.03, 0, 3.94]} />
      <Unit geometry={nodes.Unit_L103a.geometry} name="Unit_L1.03a" position={[8.5, 0, 3.56]} />
      <Unit geometry={nodes.Unit_L105.geometry} name="Unit_L1.05" position={[4.87, 0, 3.84]} />
      <Unit geometry={nodes.Unit_L106.geometry} name="Unit_L1.06" position={[1.18, 0, 3.93]} />
      <Unit geometry={nodes.Unit_L107.geometry} name="Unit_L1.07" position={[-2.52, 0, 2.06]} />
      <Unit geometry={nodes.Unit_L108.geometry} name="Unit_L1.08" position={[-4.82, 0, 1.74]} />
      <Unit geometry={nodes.Unit_L109.geometry} name="Unit_L1.09" position={[-6.15, 0, 1.3]} />
      <Unit geometry={nodes.Unit_L111.geometry} name="Unit_L1.11" position={[-13.63, 0, -4.25]} />
      <Unit geometry={nodes.Unit_L112a.geometry} name="Unit_L1.12a" position={[-12.13, 0, -4.91]} />
      <Unit geometry={nodes.Unit_L113.geometry} name="Unit_L1.13" position={[-12.52, 0, -8.33]} />
      <Unit geometry={nodes.Unit_L1xx01.geometry} name="Unit_L1.xx01" position={[-11.63, 0, -10.43]} />
      <Unit geometry={nodes.Unit_L1xx02.geometry} name="Unit_L1.xx02" position={[-9.05, 0, -1.11]} />
      <Unit geometry={nodes.Unit_L1K03A.geometry} name="Unit_L1.K03A" position={[-7.52, 0, -7.74]} />
      <Unit geometry={nodes.Unit_L1K02.geometry} name="Unit_L1.K02" position={[-7.09, 0, -3]} />
      <Unit geometry={nodes.Unit_L1xx03.geometry} name="Unit_L1.xx03" position={[-5.41, 0, -4.69]} />
      <Unit geometry={nodes.Unit_L1xx04.geometry} name="Unit_L1.xx04" position={[-4.09, 0, -1.96]} />
      <Unit geometry={nodes.Unit_L1K06.geometry} name="Unit_L1.K06" position={[-2.16, 0, -1.05]} />
      <Unit geometry={nodes.Unit_L1K07.geometry} name="Unit_L1.K07" position={[6.02, 0, -0.79]} />
      <Unit geometry={nodes.Unit_L1K09.geometry} name="Unit_L1.K09" position={[11.69, 0, -1.35]} />
      <Unit geometry={nodes.Unit_L1K10.geometry} name="Unit_L1.K10" position={[13.43, 0, -1.35]} />
      <Unit geometry={nodes.Unit_L1K11.geometry} name="Unit_L1.K11" position={[14.74, 0, -1.82]} />
      <Unit geometry={nodes.Unit_L1K08.geometry} name="Unit_L1.K08" position={[9.33, 0, -2.7]} />
      <Unit geometry={nodes.Unit_L1xx05.geometry} name="Unit_L1.xx05" position={[-1.23, 0, -4.59]} />
      <Unit geometry={nodes.Unit_L116.geometry} name="Unit_L1.16" position={[-0.69, 0, -3.59]} />
      <Unit geometry={nodes.Unit_L117.geometry} name="Unit_L1.17" position={[1.84, 0, -4.32]} />
      <Unit geometry={nodes.Unit_L118.geometry} name="Unit_L1.18" position={[4.53, 0, -4.1]} />
      <Unit geometry={nodes.Unit_L119.geometry} name="Unit_L1.19" position={[6.04, 0, -3.48]} />
      <Unit geometry={nodes.Unit_L120.geometry} name="Unit_L1.20" position={[9.51, 0, -4.9]} />
      <Unit geometry={nodes.Unit_L121.geometry} name="Unit_L1.21" position={[11.4, 0, -5.85]} />
      <Unit geometry={nodes.Unit_L122.geometry} name="Unit_L1.22" position={[13.21, 0, -5.22]} />
      <Unit geometry={nodes.Unit_L123.geometry} name="Unit_L1.23" position={[14.08, 0, -5.93]} />
      <Unit geometry={nodes.Unit_L125.geometry} name="Unit_L1.25" position={[17.76, 0, -4.27]} />
      <Unit geometry={nodes.Unit_L1C01.geometry} name="Unit_L1.C01" position={[20.77, 0, -0.71]} />
      <Unit geometry={nodes.Unit_L110.geometry} name="Unit_L1.10" position={[-7, 0, 5.4]} />
      <mesh material={materials['Lift.Normal']} geometry={nodes.Lift_L12.geometry} position={[7.08, 0, -6.34]} />
      <mesh material={materials['Lift.Normal']} geometry={nodes.Lift_L11.geometry} position={[-6.56, 0, -9.26]} />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L11.geometry}
        position={[13.09, 0.47, -3.25]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L12.geometry}
        position={[13.09, 0.47, -2.93]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L13.geometry}
        position={[-7.78, 0.47, -4.53]}
        rotation={[0, 1.13, Math.PI]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L14.geometry}
        position={[-8.06, 0.47, -4.66]}
        rotation={[0, 1.13, Math.PI]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L15.geometry}
        position={[-8.72, -0.33, -5.01]}
        rotation={[-Math.PI, -1.13, 0]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L16.geometry}
        position={[-8.43, -0.33, -4.87]}
        rotation={[-Math.PI, -1.13, 0]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L18.geometry}
        position={[12.23, -0.33, -3.24]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        material={materials['Escalator.Normal']}
        geometry={nodes.Escalator_L17.geometry}
        position={[12.23, -0.33, -2.93]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        material={materials['Services.Normal']}
        geometry={nodes.Service_L11.geometry}
        position={[18.66, 0, 3.29]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Services.Normal']}
        geometry={nodes.Service_L12.geometry}
        position={[-16.88, 0, -4.85]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        material={materials['Utilities.Normal']}
        geometry={nodes.Utilities_L11.geometry}
        position={[-0.26, 0, 1.94]}
      />
      <mesh material={materials.Floor} geometry={nodes.Floor.geometry} position={[0.01, 0, 0]} receiveShadow />
      <mesh material={materials['Others.Normal']} geometry={nodes.Others_L11.geometry} position={[19.53, 0, -2.01]} />
      <GrayArea geometry={nodes.NoEntry_L11.geometry} position={[18.94, 0, 5.4]} receiveShadow />
      <Logo
        material={materials['HarveyNorman.Normal']}
        geometry={nodes.Logo_HarveyNorman.geometry}
        position={[-6.6, 1, 7.22]}
        connectTo="Unit_L1.10"
      />
      <Logo position={[15.8, 1, 8.1]} connectTo="Unit_L1.02">
        <mesh material={materials['Ace.Normal']} geometry={nodes['Curve.001_0'].geometry} />
        <mesh material={materials['Hardware.Normal']} geometry={nodes['Curve.001_1'].geometry} />
      </Logo>
      <group position={[-8.32, 1, -4.18]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.044_0'].geometry} />
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.044_1'].geometry} />
      </group>
      <group position={[-12.27, 1, 6.4]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.038_0'].geometry} />
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.038_1'].geometry} />
      </group>
      <group position={[12.56, 1, -2.53]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.045_0'].geometry} />
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.045_1'].geometry} />
      </group>
      <group position={[-6.59, 1, -8.73]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.037_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.037_1'].geometry} />
      </group>
      <group position={[7.06, 1, -5.79]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.046_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.046_1'].geometry} />
      </group>
      <group position={[-16.88, 1, -4.21]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.018_0'].geometry} />
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.018_1'].geometry} />
      </group>
      <group position={[-17.38, 1, -3.17]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.032_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.032_1'].geometry} />
      </group>
      <group position={[-16.39, 1, -5.27]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.013_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.013_1'].geometry} />
      </group>
      <group position={[18.62, 1, 3.83]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.003_0'].geometry} />
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.003_1'].geometry} />
      </group>
      <group position={[18.63, 1, 5.04]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.004_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.004_1'].geometry} />
      </group>
      <group position={[18.63, 1, 2.64]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh material={materials['IconBlue.Normal']} geometry={nodes['Curve.005_0'].geometry} />
        <mesh material={materials['IconWhite.Normal']} geometry={nodes['Curve.005_1'].geometry} />
      </group>
      <mesh material={materials['IconBlue.Normal']} geometry={nodes.Text_L11.geometry} position={[-19.37, 0, -3.3]} />
      <mesh material={materials['IconBlue.Normal']} geometry={nodes.Text_L22.geometry} position={[-6.94, 0, -12.32]} />
      <mesh material={materials['IconBlue.Normal']} geometry={nodes.Text_L23.geometry} position={[20.4, 0, -5.2]} />
    </group>
  )
}
